apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: ${APP_NAME}
  namespace: default
spec:
  autoscaling:
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
  resources:
    limits:
      cpu: 1
    requests:
      cpu: 200m
  applicationImage: ${APP_IMAGE_URL}
  pullPolicy: Always
  service:
    type: LoadBalancer
    port: 9080
    ports:
      - port: 9443
  serviceability:
    volumeClaimName: my-azurefile
  env:
  - name: CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: oidc-secret
        key: client.id
  - name: CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: oidc-secret
        key: client.secret
  - name: TENANT_ID
    valueFrom:
      secretKeyRef:
        name: oidc-secret
        key: tenant.id
